version: "3.7"
services:

  rabbitmq:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "rabbitmq"
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    hostname: stats
    environment:
      RABBITMQ_DEFAULT_USER: ErickDK
      RABBITMQ_DEFAULT_PASS: killerkiller
    networks:
      rabbitmq_net:
        aliases:
          - rabbitmq_host

  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  chronograf:
    image: chronograf:latest
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}


  grafana:
    image: grafana/grafana:7.3.7     
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    user: "0"
    links:
      - influxdb
    volumes:
      - ./data_grafana:/var/lib/grafana

volumes:
  influxdb-storage:
  chronograf-storage:  
  data_grafana:
  data: {}
networks:
  rabbitmq_net:
    name: rabbitmq_network
    driver: bridge


      
      