version: "3.7"
services:
  rabbitmq:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "rabbitmq"
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    hostname: stats
    environment:
      RABBITMQ_DEFAULT_USER: ErickDK
      RABBITMQ_DEFAULT_PASS: killerkiller
    networks:
      rabbitmq_net:
        aliases:
          - rabbitmq_host
volumes:
  data: {}
networks:
  rabbitmq_net:
    name: rabbitmq_network
    driver: bridge


      
      